version: "3.5"

volumes:
  node_data: {}

networks:
  node-net:
    external: false

services:
  ################################ REACTJS ################################
  react:
    image: node:16.3.0-alpine
    container_name: reactjs
    expose:
      - 3000
    networks:
      - node-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000
    volumes:
      - "./client/:/home/app/"
    depends_on:
      - node
    command: sh -c "cd /home/app && npm install --save"

  ################################ NODEJS ################################
  node:
    image: node:16.3.0-alpine
    container_name: nodejs
    expose:
      - 5000
    networks:
      - node-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 5000:5000
    volumes:
      - "./server/:/home/app/"
    command: sh -c "cd /home/app && npm install --save"
