version: "3.4"

volumes:
  node_data: {}

networks:
  node-net:
    external: false

services:
################################ NGINX ################################
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80

################################ REACTJS ################################
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    expose:
      - 3000
    networks:
      - node-net
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./client:/app
    environment:
      - NODE_ENV=production
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - server
    ports:
      - 3000:3000
      
################################ NODEJS ################################
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    expose:
      - 5000
    networks:
      - node-net
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 5000:5000
