version: '3.3'

services:
    sonarqube:
        image: sonarqube
        restart: always
        ports:
            - '9000:9000'
        networks:
            - sonarNet

networks:
    sonarNet:
        driver: bridge
